import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    paddingTop: 50,
    paddingBottom: 80,
  },
  scrollContainer: {
    paddingHorizontal: 28,
    paddingBottom: 120,
    marginTop: 40,
  },
  header: {
    fontSize: 28,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 30,
    paddingLeft: 24,
    borderLeftWidth: 6,
    borderLeftColor: "#1E90FF",
    letterSpacing: 1.5,
  },
  card: {
    backgroundColor: "rgba(45, 45, 45, 0.85)",
    borderRadius: 32,
    paddingVertical: 24,
    paddingHorizontal: 24,
    marginBottom: 26,
    marginHorizontal: 20,
    alignItems: "stretch",
    borderWidth: 1.2,
    borderColor: "rgba(255, 255, 255, 0.06)",
    shadowColor: "rgba(0, 0, 0, 0.8)",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    elevation: 12,
  },
  input: {
    backgroundColor: "rgba(30, 30, 30, 0.9)",
    color: "#fff",
    marginBottom: 16,
    padding: 14,
    borderRadius: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  label: {
    color: "#bbb",
    fontSize: 16,
    marginBottom: 8,
  },
  value: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  editBtn: {
    backgroundColor: "#1E90FF",
    paddingVertical: 16,
    borderRadius: 32,
    marginTop: 20,
    shadowColor: "rgba(0, 0, 0, 0.7)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 10,
  },
  editText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 18,
  },
  saveBtn: {
    backgroundColor: "#1E90FF",
    paddingVertical: 16,
    borderRadius: 32,
    marginTop: 20,
    shadowColor: "rgba(0, 0, 0, 0.7)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 10,
  },
  saveText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 18,
  },
  deleteBtn: {
    backgroundColor: "#ff4444",
    paddingVertical: 16,
    borderRadius: 32,
    marginTop: 20,
    shadowColor: "rgba(0, 0, 0, 0.7)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 10,
  },
  deleteText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 18,
  },
  toggleLink: {
    marginTop: 14,
    alignItems: "center",
  },
  toggleText: {
    color: "#1E90FF",
    fontSize: 15,
  },
  loading: {
    color: "#fff",
    textAlign: "center",
    marginTop: 50,
    fontSize: 18,
  },
  actionButton: {
    marginTop: 20,
  },
  nfcBtn: {
    backgroundColor: "#1E90FF",
    paddingVertical: 16,
    borderRadius: 32,
    marginTop: 20,
    shadowColor: "rgba(0, 0, 0, 0.7)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 10,
  },
  nfcText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 18,
  },
});

export default styles;
